server:
  port: 9499
  servlet:
    context-path: /api

spring:
  application:
    name: ninhxa-report
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  
  datasource:
    url: jdbc:mysql://localhost:9498/ninhxa_report?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ninhxa_user
    password: ninhxa_pass123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

# JWT Configuration
jwt:
  secret: ninhxa-report-secret-key-2024-bacninh-government-very-secure-key-256-bits
  expiration: 86400000 # 24 hours in milliseconds

# File Upload Configuration
app:
  auth:
    super-password: admin2025
  upload:
    dir: uploads  # Directory to store uploaded files (relative to project root or absolute path)

# Logging
logging:
  level:
    root: INFO
    vn.gov.bacninh: DEBUG
    org.springframework.security: DEBUG

bacninh:
  sso:
    token-url: https://ssobn.bacninh.gov.vn/realms/BacNinh/protocol/openid-connect/token
    client-id: app-gov-web
    client-secret: Wd7PQ9pHv5a0imf9Jvv4qIqkunH1kmve
    basic-authorization: Basic dGFpLWtob2FuLWdvdjpwSWNYYXZLRHR5V1RtMk15SmZTYWxabUR2MkJOanMycg==

zalo:
  oauth:
    app-id: 3283449234241152035
    secret: xMYjMV5P35kbF5PNpjU3